version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile
    # macは左(空いている任意のポート)を指定し、dockerは右(コンテナのポート)を指定する
    ports:
      - "5173:5173"
    volumes:
      # コンテナのnode_modulesをマウントしているので
      # ホスト側のnode_modulesで変更があったて反映されない
      # - node_modules:/app/node_modules
      # ホスト側の.ディレクトリをコンテナのappディレクトリにマウント
      - .:/app
      # 上記node_modulesの設定不要かも
    environment:
      - MYSQL_USER=app
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql
  phpMyAdmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=app
      - PMA_PASSWORD=password
    depends_on:
      - db

volumes:
  mysql:
  node_modules: